name: "Release"

on:
  release:
    types:
      - "published"

permissions:
  contents: write

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Adjust version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/google_pollen/manifest.json"
